=== Vickers-Zhu/Meetings_XML/MeetingsLibrary/Meetings.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:bs="http://www.example.org/meetings"
        targetNamespace="http://www.example.org/meetings"
        elementFormDefault="qualified">
  <element name="pastures">
    <complexType>
      <sequence>
        <element name="meetings">
          <complexType>
            <sequence>
              <element name="meeting" type="bs:meeting" minOccurs="2" maxOccurs="unbounded"/>
            </sequence>
          </complexType>
        </element>
        <element name="pasture" type="bs:pasture" maxOccurs="unbounded"/>
        <element name="centaur" type="bs:centaur" maxOccurs="unbounded"/>
        <element name="minotaur" type="bs:minotaur" maxOccurs="1"/>
      </sequence>
    </complexType>
  </element>
  <complexType name="meeting">
    <sequence>
      <element name="participant" type="string" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="location" use="required"/>
  </complexType>
  <complexType name="pasture">
    <sequence>
      <element name="name" type="string" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="area" />
  </complexType>
  <complexType name="taur">
    <attribute name="name" type="string" use="required" />
    <attribute name="age" type="integer" use="optional" />
    <attribute name="id" type="integer" use="required" />
  </complexType>
  <complexType name="centaur">
    <complexContent>
      <extension base="bs:taur">
        <sequence>
          <element name="beard" minOccurs="0"/>
          <element name="mustache" minOccurs="0"/>
          <element name="whiskers" minOccurs="0"/>
        </sequence>
      </extension>   
    </complexContent>   
  </complexType>
  <complexType name="minotaur">
    <complexContent>
      <extension base="bs:taur">
        <attribute name="mass" use="optional"/>     
      </extension>     
    </complexContent>  
  </complexType>
</schema>

=== Vickers-Zhu/Meetings_XML/MeetingsLibrary/pasture-example.xml
<?xml version="1.0" encoding="utf-8"?>
<pastures xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.org/meetings"
          xsi:schemaLocation="http://www.example.org/meetings Meetings.xsd">
  <meetings>
    <meeting location="AA">
      <participant>1</participant>
      <participant>2</participant>
    </meeting>
    <meeting location="XX-YX-ZA">
      <participant>4</participant>
      <participant>2</participant>
    </meeting>
  </meetings>
  <pasture area="20.00">
    <name>XX-YX-ZA</name>
    <name>XX-YX-ZB</name>
    <name>AA</name>
  </pasture>
  <pasture area="31.03">
    <name>AA-BB-CC-DD</name>
  </pasture>
  <pasture area="31.12">
    <name>WQ-AZ-XX</name>
    <name>SS</name>
    <name>AB-CD-FG-AN-PQ</name>	    
  </pasture>
  <centaur name="Sonny" age="23" id="1">
    <beard/>
    <mustache/>
  </centaur>
  <centaur name="Roger" age="21" id="2">
    <beard/>
    <whiskers/>
  </centaur>
  <minotaur name="Larry" age="77" id="4" mass="785"/>
</pastures>
